spring.application.name=Smart-Agriculture-system

# H2 Database Configuration
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Hibernate
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update

# H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console


spring.ai.openai.api-key=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
spring.ai.openai.base-url=https://api.groq.com/openai
spring.ai.openai.chat.options.model=llama-3.3-70b-versatile

# Ml
ml.api.url=http://localhost:8000/predict
