spring.application.name=Smart-Agriculture-system

# DataBase 
spring.datasource.url=jdbc:postgresql://localhost:5432/smart_agriculture
spring.datasource.username=postgres
spring.datasource.password=Sidd@2004
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate Configuration
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Connection Pool (HikariCP)
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.maximum-pool-size=5


# Ml URL
ml.crop.api.url=http://localhost:5000/api/predict-crop
ml.disease.api.url=http://localhost:5000/api/detect-disease


# Image

project.image=${user.home}/smart-agriculture/images/


spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB


logging.level.com.SmartAgriculture.Cropp=DEBUG
logging.level.org.springframework.web.client.RestTemplate=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# Spring Ai
spring.ai.openai.api-key=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
spring.ai.openai.base-url=https://api.groq.com/openai
spring.ai.openai.chat.options.model=llama-3.3-70b-versatile

# Security
spring.app.jwtSecret=mySecretKey123912738aopsgjnspkmndfsopkvajoirjg94gf2opfng2moknm
spring.app.jwtExpirationMs=3000000
spring.cropp.app.jwtCookies=springBootEcom
