spring.application.name=Smart-Agriculture-system

# DataBase 
spring.datasource.url=jdbc:postgresql://localhost:5432/smart_agriculture
spring.datasource.username=${DB_USER_NAME}
spring.datasource.password=${DB_PWD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate Configuration
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

# Connection Pool (HikariCP)
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.maximum-pool-size=5


# Ml URL
ml.crop.api.url=http://localhost:5000/api/predict-crop
ml.disease.api.url=http://localhost:5000/api/detect-disease


# Image
project.image=${user.home}/smart-agriculture/images/
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB


# logging.level.org.springframework=DEBUG
# logging.level.org.hibernate.SQL=DEBUG
# logging.level.org.springframework.security=DEBUG
# logging.level.com.ecommerce.project=DEBUG

# Spring Ai
spring.ai.openai.api-key=${API_KEY}
spring.ai.openai.base-url=https://api.groq.com/openai
spring.ai.openai.chat.options.model=llama-3.3-70b-versatile

# Security
spring.app.jwtSecret=${JWT_SECRET}    mySecretKey123912738aopsgjnspkmndfsopkvajoirjg94gf2opfng2moknm
spring.app.jwtExpirationMs=3000000
spring.cropp.app.jwtCookies=smartAgricultureSytem


# Email
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username= youremail123@gmail.com
spring.mail.password=${MAIL_APP_PASSWORD}


spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
