INSERT INTO roles (role_name) 
SELECT 'ROLE_FARMER' WHERE NOT EXISTS (SELECT 1 FROM roles WHERE role_name = 'ROLE_FARMER');

INSERT INTO roles (role_name) 
SELECT 'ROLE_AGRONOMIST' WHERE NOT EXISTS (SELECT 1 FROM roles WHERE role_name = 'ROLE_AGRONOMIST');

INSERT INTO roles (role_name) 
SELECT 'ROLE_ADMIN' WHERE NOT EXISTS (SELECT 1 FROM roles WHERE role_name = 'ROLE_ADMIN');